"""Write AGENTS.md (read by ChatGPT Codex and other coding agents) from CLAUDE.md + the skills.

    python scripts/make_agents_md.py

One source of truth: the skills in .claude/skills/. Claude Code loads them natively; other
agents get the same instructions through AGENTS.md, which lists every skill with its file so
the agent reads it when the task matches. Re-run after changing CLAUDE.md or any skill.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def skill_index():
    rows = []
    base = os.path.join(ROOT, ".claude", "skills")
    for name in sorted(os.listdir(base)):
        p = os.path.join(base, name, "SKILL.md")
        if not os.path.exists(p):
            continue
        head = open(p, encoding="utf-8").read().split("---")
        desc = ""
        if len(head) > 2:
            m = re.search(r"^description:\s*(.+)$", head[1], re.M)
            desc = m.group(1).strip().strip('"') if m else ""
        rows.append((name, desc, f".claude/skills/{name}/SKILL.md"))
    return rows


def main():
    claude = open(os.path.join(ROOT, "CLAUDE.md"), encoding="utf-8").read()
    body = claude.replace("# Reel Studio — instructions for Claude", "# Reel Studio — instructions for the AI editor")
    body = body.replace("## Skills (in .claude/skills)", "## Skills (in .claude/skills) — see the index below")
    out = ["<!-- Generated by scripts/make_agents_md.py from CLAUDE.md and .claude/skills. Do not edit by hand. -->",
           "", body.strip(), "", "## Skill index (read the file before doing that kind of task)", "",
           "These are the same step-by-step playbooks Claude uses. When a request matches a description,",
           "open that SKILL.md and follow it exactly (commands, order, rules). Where a skill mentions a",
           "Claude-only tool (e.g. publishing a page), use your nearest equivalent or give the user the",
           "local file/link instead.", ""]
    for name, desc, path in skill_index():
        out.append(f"- **{name}** — {desc} → `{path}`")
    out += ["", "## Running commands", "",
            "Everything runs locally with `python -m engine <command>` from this folder (Windows: `py -m engine`).",
            "Tests: `python -m pytest tests -q`.", ""]
    open(os.path.join(ROOT, "AGENTS.md"), "w", encoding="utf-8").write("\n".join(out))
    print("AGENTS.md written:", len(skill_index()), "skills")


if __name__ == "__main__":
    main()
